---
title: "IcoLL2026"
description: |
  Joint conference of the 4th Iconicity Seminar (IcoSem) and the 15th International Symposium on Iconicity in Language and Literature (ILL)
site: distill::distill_website
---

```{r setup, include = FALSE}
library(knitr)
library(readxl)
library(tidyverse)

opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')
```

**IcoLL2026** is the joint conference of the 4th [Iconicity Seminar (IcoSem)](https://ianjoo.github.io/icosem) and the 15th [International Symposium on Iconicity in Language and Literature (ILL)](https://www.iconicity.uzh.ch/en). For the first time, the two international conferences on iconicity will take place together on **21-23 February 2026** hosted by the **Nagoya University Graduate School of Humanities**.

# Invited speakers

 * [Mutsumi Imai](https://researchmap.jp/imai_mutsumi?lang=en)
 * [Noburo Saji](https://researchmap.jp/nonsvch?lang=en)
 * [Pamela Perniss](https://www.pernipa.myzen.co.uk)
 * [Neil Cohn](https://www.visuallanguagelab.com/neilcohn)

# Call for papers

Theme: **Variations and Dynamics in Iconicity**
 
We invite abstracts of any academic work on **iconicity**, the resemblance between form and meaning, in language or literature. We particularly invite contributions that explore the multifaceted nature of iconicity, encompassing its variations and dynamics across different conceptual domains, languages, cultures, and developmental stages. Topics of interest include, but are not limited to, the following:
 
 * Iconicity in the speech signal (sound symbolism, phonaesthemes, ideophones)
 * Iconicity in grammar and text
 * Iconicity in literature
 * Iconicity in sign languages
 * Iconicity in gestures
 * Iconicity in pictures and other visual media
 * Iconicity in music
 * Iconicity in narration
 * Iconicity in imagination (mental imagery)
 * Iconicity across sensory modalities (multimodality and cross-modality)
 * Iconicity in language evolution
 * Iconicity in child development
 * Iconicity among different forms of intelligence (animals, humans, AI, etc.)

Please send a 2-page abstract (including everything) in the following format:

* A4 paper
* 2.5cm margin
* 12pt Times New Roman

Please submit your anonymized abstract to Ian Joo at joo@res.otaru-uc.ac.jp. Your abstract will then go through a single-blind review by two anonymous reviewers.

The deadline is **31 August 2025**, but we encourage each participant to **submit as soon as you are ready to**, as decisions will be communicated to you on a rolling basis within two weeks from your submission (and not necessarily after the deadline). This will allow you to plan your trip well in advance.

Each submission will be allocated as either an oral presentation (20min talk + 10min Q&A) or a poster presentation, based on the review and the presenter's preference. Only one abstract submission is permitted per each first author - there is no restriction on the number of abstracts as a non-first author.

After the conference, the presenters will be invited to submit a post-conference proceedings paper to the [Iconicity in Language and Literature](https://benjamins.com/catalog/ill) series (John Benjamins).

# Format of the conference
IcoLL2026 is an in-person conference without virtual participation, although some virtual presentations may be permitted in exceptional cases.

Due to the difficulty of finding an English-to-JSL interpreter with expertise in linguistics and literature, we will unfortunately not be able to provide interpretation in Japanese Sign Language. In order to increase accessibility, however, we will provide live caption in English via Microsoft Teams.

# Participation fee
The participation fee is 8,000 yen for students and 15,000 yen for non-students, to be paid by cash on site.

# About Nagoya

[Nagoya](https://en.wikipedia.org/wiki/Nagoya) is a city located in central Japan, easily accessible from Tokyo or Osaka.

The nearest international airports are:

 * Chubu Centrair International Airport (Nagoya) - 1 hour to Nagoya University
 * Kansai International Airport (Osaka) - 3 hours
 * Haneda Airport (Tokyo) - 3 hours
 * Narita International Airport (Tokyo) - 4 hours
 
The attractions in Nagoya and nearby cities include:

 * [Nagoya Castle](https://www.nagoyajo.city.nagoya.jp/en/)
 * [Hisaya-Odori Park](https://mitsui-shopping-park.com/urban/hisaya/)
 * [Port of Nagoya Aquarium](https://nagoyaaqua.jp/english/)
 * [Ghibli Park](https://ghibli-park.jp/en/) (in Nagakute)
 * [Inuyama Castle](https://inuyamajo.jp/) (in Inuyama)
 
We plan to arrange a group tour to the Ghibli Park for the participants who are interested. Please let the organizers know well before the conference, as the park is very popular and the tickets typically need to be booked two months in advance.

# Organizers

 * [Hinano Iida](https://sites.google.com/view/hinanoiida)
 * [Ian Joo](https://ianjoo.github.io)
 * [Kimi Akita](https://sites.google.com/site/akitambo/Home)
 
# Links

Join our [Facebook group for iconicity](https://www.facebook.com/groups/lingicon)