---
title: 'IcoLL2026 program'
author: 'Organizers: Hinano Iida, Ian Joo, Kimi Akita'
date: "As of `r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
header-includes: 
  - \usepackage{booktabs} 
  - \usepackage{longtable}
geometry: 
  - margin = 2cm
  - a4paper
  - landscape
mainfont: Times New Roman
fontsize: 11pt
---

```{r, echo = FALSE, include = FALSE}
library(readxl)
library(knitr)
library(tidyverse)
```

```{r, echo = FALSE}
options(knitr.kable.NA = '')

Oral <- read_xlsx('IcoLL2026.xlsx') %>% 
  filter(Type == 'Oral') %>% 
  select(Author, Title, Theme, Day, Room, Session) %>% 
  mutate(AuthorTitle = paste0(Title, " (", Author, ")")) %>% 
  mutate(ThemeAuthorTitle = paste0("[", Theme, "] ", AuthorTitle)) %>% 
  select(ThemeAuthorTitle, Day, Room, Session) %>% 
  group_by(Day, Room, Session) %>% 
  mutate(Order = row_number()) %>% 
  arrange(Day, Room, Session, Order) %>% 
  pivot_wider(names_from = Room, values_from = ThemeAuthorTitle) %>% 
  rename(`IB011` = `1`, `IB013` = `2`, `IB014` = `3`, `IB015` = `4`)

Program <- read_xlsx('IcoLL2026program.xlsx') %>% 
  left_join(Oral, by = c('Day', 'Session', 'Order')) %>% 
  select(-Session, -Order) %>% 
  mutate(IB015 = 
           ifelse(grepl('Plenary talk',
                        Schedule),
                  gsub('Plenary talk: ',
                        '', Schedule),
                  IB015)) %>% 
  mutate(Schedule = ifelse(grepl('Plenary talk',
                        Schedule),
                      'Plenary talk',
                       Schedule)) %>% 
    mutate(IB015 = 
           ifelse(Schedule == 'Opening remarks',
                  'Disentangling iconicity (Hinano Iida)',
                  IB015)) %>% 
  select(Day, Time, Schedule, IB015, IB011, IB013, IB014)

Poster <- read_xlsx('IcoLL2026.xlsx') %>% 
  filter(Type == 'Poster') %>% 
  select(Author, Title, Day) %>% 
  arrange(Day, Title, Author) %>% 
  mutate(`Title (Author)` = paste0(Title, " (", Author, ")")) %>% 
  select(-Author, -Title) %>% 
  group_by(Day) %>% 
  mutate(No. = row_number()) %>% 
  relocate(Day, No., `Title (Author)`)

Day1 <- Program %>% 
  filter(Day == 1) %>% 
  select(-Day)

Day2 <- Program %>% 
  filter(Day == 2) %>% 
  select(-Day)

Day3 <- Program %>% 
  filter(Day == 3) %>% 
  select(-Day)
```

\begin{center}
\bf 21 February (Day 1)
\end{center}

```{r, echo = FALSE, warning = FALSE}
kable(Day1, 'latex', booktabs = TRUE, longtable = TRUE,
      align = c('r', 'p{4.3cm}', 'p{4.3cm}', 'p{4.3cm}', 'p{4.3cm}', 'p{4.3cm}'))
```

\pagebreak

\begin{center}
\bf 22 February (Day 2)
\end{center}

```{r, echo = FALSE, warning = FALSE}
kable(Day2, 'latex', booktabs = TRUE, longtable = TRUE,
      align = c('r', 'p{4.3cm}', 'p{4.3cm}', 'p{4.3cm}', 'p{4.3cm}', 'p{4.3cm}'))
```

\pagebreak

\begin{center}
\bf 23 February (Day 3)
\end{center}

```{r, echo = FALSE, warning = FALSE}
kable(Day3, 'latex', booktabs = TRUE, longtable = TRUE,
      align = c('r', 'p{4.3cm}', 'p{4.3cm}', 'p{4.3cm}', 'p{4.3cm}', 'p{4.3cm}'))
```

\pagebreak

\begin{center}
\bf List of poster presentations
\end{center}

```{r, echo = FALSE, warning = FALSE}
kable(Poster, 'latex', booktabs = TRUE, longtable = TRUE,
      align = c('r', 'r', 'p{21cm}'))
```


\thispagestyle{empty}
